### ISSUE TITLE
Font loading causes Flash of Unstyled Content

### ISSUE THREAD

**Issue by rcorre** [barlog-m/oceanic-zen#3]
When I load a page using this theme, it briefly renders without the custom fonts, then there's a jarring [FOUC](https://stackoverflow.com/questions/3221561/eliminate-flash-of-unstyled-content) as the font arrives and all the text rearranges itself (I'm repeatedly hard-refreshing the page here):

https://user-images.githubusercontent.com/2496231/149799234-6d2a3cb6-4d91-4f00-9a4c-be14b23dab71.mp4

The linked SO question has some solutions, though relying on javascript seems less than ideal (I liked that this theme was JS-free).

Also, it for some reason isn't so bad on the demo page, it seems to cache more aggressively or something, and only triggers when I first visit or hard refresh. However, when I run locally, it happens every time I visit a new page.

**Comment by barlog-m** [comment]
Hi. Thank you for issue.
How to reproduce this behaviour?
What browser do you use?
Do you use JS or disable it?

**Comment by rcorre** [comment]
> How to reproduce this behaviour?

1. Clone this repo
2. Run `zola serve` (I had to remove the table of contents from the markdown-here file first)
3. Visit `localhost:1111`
4. Click on the links in your browser

> What browser do you use?

[qutebrowser](https://github.com/qutebrowser/qutebrowser).

I just tested firefox and I don't see a FOUC, so maybe it is a browser issue. Oops!

> Do you use JS or disable it?

I disable it, though enabling does not resolve the issue.

In my local project, I was able to work around it by adding preload links for all my fonts:

```diff
diff --git a/templates/index.html b/templates/index.html
new file mode 100644
index 0000000..18ec380
--- /dev/null
+++ b/templates/index.html
@@ -0,0 +1,10 @@
+{% extends "oceanic-zen/templates/index.html" %}
+
+{% block css %}
+<link rel="preload" href="{{ get_url(path="fonts/hack-regular-subset.woff2", trailing_slash=false) | safe }}" as="font" type="font/woff2" crossorigin="anonymous">
+<link rel="preload" href="{{ get_url(path="fonts/hack-italic-subset.woff2", trailing_slash=false) | safe }}" as="font" type="font/woff2" crossorigin="anonymous">
+<link rel="preload" href="{{ get_url(path="fonts/hack-bold-subset.woff2", trailing_slash=false) | safe }}" as="font" type="font/woff2" crossorigin="anonymous">
+<link rel="preload" href="{{ get_url(path="fonts/hack-bolditalic-subset.woff2", trailing_slash=false) | safe }}" as="font" type="font/woff2" crossorigin="anonymous">
+<link rel="stylesheet" href="{{ get_url(path="hack-subset.css", trailing_slash=false) | safe }}">
+<link rel="stylesheet" href="{{ get_url(path="style.css", trailing_slash=false) | safe }}">
+{% endblock css %}
```

That increases the page load time a bit. I'm not sure if there's a better way
around it, or if the best approach is to simply not use custom fonts at all?

Thanks for the nice theme!
